//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ExceptionLog = new HashSet<ExceptionLog>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int City { get; set; }
        public string PostalCode { get; set; }
        public int Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int ShoppingCartID { get; set; }
        public bool IsAcountSuspended { get; set; }
        public System.DateTime DateEntered { get; set; }
    
        public virtual ICollection<ExceptionLog> ExceptionLog { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
