//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public int IsTransactionComplete { get; set; }
        public string ErrorLog { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int CustomerID { get; set; }
        public int PaymentID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
