//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ShoppingCartDetail = new HashSet<ShoppingCartDetail>();
        }
    
        public int ProductID { get; set; }
        public System.Guid UniqueId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public double Rating { get; set; }
        public decimal Price { get; set; }
        public int StockCount { get; set; }
        public Nullable<System.Guid> ImageId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<ShoppingCartDetail> ShoppingCartDetail { get; set; }
    }
}
