//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartDetail
    {
        public int ShoppingCartDetailId { get; set; }
        public int ShoppingCartId { get; set; }
        public int ProductId { get; set; }
        public int ItemCount { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
